version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: deploy/web.Dockerfile
    ports:
      - "80:80"            # EB expects exactly one service publishing host:80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      PORT: "8000"
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s
